FROM ubuntu
WORKDIR /opt
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.zip /opt/
RUN apt update -y
RUN apt install unzip -y
RUN unzip /opt/apache-tomcat-8.5.78.zip 
WORKDIR /opt/apache-tomcat-8.5.78/bin
RUN apt update -y
RUN apt install openjdk-8-jre -y
RUN chmod 777 /opt/apache-tomcat-8.5.78/bin/*
EXPOSE 8080
CMD ["/opt/apache-tomcat-8.5.78/bin/catalina.sh", "run"]

